// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: XsdTypes.proto

package edu.vanderbilt.isis.meta;

public final class XsdTypes {
  private XsdTypes() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface IDOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required bytes uuid = 1;
    boolean hasUuid();
    com.google.protobuf.ByteString getUuid();
  }
  public static final class ID extends
      com.google.protobuf.GeneratedMessage
      implements IDOrBuilder {
    // Use ID.newBuilder() to construct.
    private ID(Builder builder) {
      super(builder);
    }
    private ID(boolean noInit) {}
    
    private static final ID defaultInstance;
    public static ID getDefaultInstance() {
      return defaultInstance;
    }
    
    public ID getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.vanderbilt.isis.meta.XsdTypes.internal_static_edu_vanderbilt_isis_meta_ID_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.vanderbilt.isis.meta.XsdTypes.internal_static_edu_vanderbilt_isis_meta_ID_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required bytes uuid = 1;
    public static final int UUID_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString uuid_;
    public boolean hasUuid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.google.protobuf.ByteString getUuid() {
      return uuid_;
    }
    
    private void initFields() {
      uuid_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasUuid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, uuid_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, uuid_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static edu.vanderbilt.isis.meta.XsdTypes.ID parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.vanderbilt.isis.meta.XsdTypes.ID parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.vanderbilt.isis.meta.XsdTypes.ID parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.vanderbilt.isis.meta.XsdTypes.ID parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.vanderbilt.isis.meta.XsdTypes.ID parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.vanderbilt.isis.meta.XsdTypes.ID parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static edu.vanderbilt.isis.meta.XsdTypes.ID parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.vanderbilt.isis.meta.XsdTypes.ID parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.vanderbilt.isis.meta.XsdTypes.ID parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.vanderbilt.isis.meta.XsdTypes.ID parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.vanderbilt.isis.meta.XsdTypes.ID prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements edu.vanderbilt.isis.meta.XsdTypes.IDOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.vanderbilt.isis.meta.XsdTypes.internal_static_edu_vanderbilt_isis_meta_ID_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.vanderbilt.isis.meta.XsdTypes.internal_static_edu_vanderbilt_isis_meta_ID_fieldAccessorTable;
      }
      
      // Construct using edu.vanderbilt.isis.meta.XsdTypes.ID.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        uuid_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.vanderbilt.isis.meta.XsdTypes.ID.getDescriptor();
      }
      
      public edu.vanderbilt.isis.meta.XsdTypes.ID getDefaultInstanceForType() {
        return edu.vanderbilt.isis.meta.XsdTypes.ID.getDefaultInstance();
      }
      
      public edu.vanderbilt.isis.meta.XsdTypes.ID build() {
        edu.vanderbilt.isis.meta.XsdTypes.ID result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private edu.vanderbilt.isis.meta.XsdTypes.ID buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        edu.vanderbilt.isis.meta.XsdTypes.ID result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public edu.vanderbilt.isis.meta.XsdTypes.ID buildPartial() {
        edu.vanderbilt.isis.meta.XsdTypes.ID result = new edu.vanderbilt.isis.meta.XsdTypes.ID(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.uuid_ = uuid_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.vanderbilt.isis.meta.XsdTypes.ID) {
          return mergeFrom((edu.vanderbilt.isis.meta.XsdTypes.ID)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(edu.vanderbilt.isis.meta.XsdTypes.ID other) {
        if (other == edu.vanderbilt.isis.meta.XsdTypes.ID.getDefaultInstance()) return this;
        if (other.hasUuid()) {
          setUuid(other.getUuid());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasUuid()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              uuid_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required bytes uuid = 1;
      private com.google.protobuf.ByteString uuid_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasUuid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.google.protobuf.ByteString getUuid() {
        return uuid_;
      }
      public Builder setUuid(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        uuid_ = value;
        onChanged();
        return this;
      }
      public Builder clearUuid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        uuid_ = getDefaultInstance().getUuid();
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:edu.vanderbilt.isis.meta.ID)
    }
    
    static {
      defaultInstance = new ID(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:edu.vanderbilt.isis.meta.ID)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_edu_vanderbilt_isis_meta_ID_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_edu_vanderbilt_isis_meta_ID_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016XsdTypes.proto\022\030edu.vanderbilt.isis.me" +
      "ta\"\022\n\002ID\022\014\n\004uuid\030\001 \002(\014"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_edu_vanderbilt_isis_meta_ID_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_edu_vanderbilt_isis_meta_ID_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_edu_vanderbilt_isis_meta_ID_descriptor,
              new java.lang.String[] { "Uuid", },
              edu.vanderbilt.isis.meta.XsdTypes.ID.class,
              edu.vanderbilt.isis.meta.XsdTypes.ID.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
