// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CdbMsg.proto

package edu.vanderbilt.isis.meta;

public final class CdbMsg {
  private CdbMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .edu.vanderbilt.isis.meta.Message.MessageType type = 1;
    boolean hasType();
    edu.vanderbilt.isis.meta.CdbMsg.Message.MessageType getType();
    
    // optional .edu.vanderbilt.isis.meta.ID _id = 2;
    boolean hasId();
    edu.vanderbilt.isis.meta.XsdTypes.ID getId();
    edu.vanderbilt.isis.meta.XsdTypes.IDOrBuilder getIdOrBuilder();
    
    // optional .edu.vanderbilt.isis.meta.Assemblies assemblies = 3;
    boolean hasAssemblies();
    edu.vanderbilt.isis.meta.AssemblyInterface.Assemblies getAssemblies();
    edu.vanderbilt.isis.meta.AssemblyInterface.AssembliesOrBuilder getAssembliesOrBuilder();
    
    // repeated .edu.vanderbilt.isis.meta.Notice notices = 4;
    java.util.List<edu.vanderbilt.isis.meta.CdbMsg.Notice> 
        getNoticesList();
    edu.vanderbilt.isis.meta.CdbMsg.Notice getNotices(int index);
    int getNoticesCount();
    java.util.List<? extends edu.vanderbilt.isis.meta.CdbMsg.NoticeOrBuilder> 
        getNoticesOrBuilderList();
    edu.vanderbilt.isis.meta.CdbMsg.NoticeOrBuilder getNoticesOrBuilder(
        int index);
  }
  public static final class Message extends
      com.google.protobuf.GeneratedMessage
      implements MessageOrBuilder {
    // Use Message.newBuilder() to construct.
    private Message(Builder builder) {
      super(builder);
    }
    private Message(boolean noInit) {}
    
    private static final Message defaultInstance;
    public static Message getDefaultInstance() {
      return defaultInstance;
    }
    
    public Message getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.vanderbilt.isis.meta.CdbMsg.internal_static_edu_vanderbilt_isis_meta_Message_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.vanderbilt.isis.meta.CdbMsg.internal_static_edu_vanderbilt_isis_meta_Message_fieldAccessorTable;
    }
    
    public enum MessageType
        implements com.google.protobuf.ProtocolMessageEnum {
      INTEREST(0, 0),
      UPDATE(1, 1),
      FILL(2, 2),
      TRASH(3, 3),
      ;
      
      public static final int INTEREST_VALUE = 0;
      public static final int UPDATE_VALUE = 1;
      public static final int FILL_VALUE = 2;
      public static final int TRASH_VALUE = 3;
      
      
      public final int getNumber() { return value; }
      
      public static MessageType valueOf(int value) {
        switch (value) {
          case 0: return INTEREST;
          case 1: return UPDATE;
          case 2: return FILL;
          case 3: return TRASH;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
              public MessageType findValueByNumber(int number) {
                return MessageType.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return edu.vanderbilt.isis.meta.CdbMsg.Message.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final MessageType[] VALUES = {
        INTEREST, UPDATE, FILL, TRASH, 
      };
      
      public static MessageType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private MessageType(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:edu.vanderbilt.isis.meta.Message.MessageType)
    }
    
    private int bitField0_;
    // required .edu.vanderbilt.isis.meta.Message.MessageType type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private edu.vanderbilt.isis.meta.CdbMsg.Message.MessageType type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public edu.vanderbilt.isis.meta.CdbMsg.Message.MessageType getType() {
      return type_;
    }
    
    // optional .edu.vanderbilt.isis.meta.ID _id = 2;
    public static final int _ID_FIELD_NUMBER = 2;
    private edu.vanderbilt.isis.meta.XsdTypes.ID Id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public edu.vanderbilt.isis.meta.XsdTypes.ID getId() {
      return Id_;
    }
    public edu.vanderbilt.isis.meta.XsdTypes.IDOrBuilder getIdOrBuilder() {
      return Id_;
    }
    
    // optional .edu.vanderbilt.isis.meta.Assemblies assemblies = 3;
    public static final int ASSEMBLIES_FIELD_NUMBER = 3;
    private edu.vanderbilt.isis.meta.AssemblyInterface.Assemblies assemblies_;
    public boolean hasAssemblies() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public edu.vanderbilt.isis.meta.AssemblyInterface.Assemblies getAssemblies() {
      return assemblies_;
    }
    public edu.vanderbilt.isis.meta.AssemblyInterface.AssembliesOrBuilder getAssembliesOrBuilder() {
      return assemblies_;
    }
    
    // repeated .edu.vanderbilt.isis.meta.Notice notices = 4;
    public static final int NOTICES_FIELD_NUMBER = 4;
    private java.util.List<edu.vanderbilt.isis.meta.CdbMsg.Notice> notices_;
    public java.util.List<edu.vanderbilt.isis.meta.CdbMsg.Notice> getNoticesList() {
      return notices_;
    }
    public java.util.List<? extends edu.vanderbilt.isis.meta.CdbMsg.NoticeOrBuilder> 
        getNoticesOrBuilderList() {
      return notices_;
    }
    public int getNoticesCount() {
      return notices_.size();
    }
    public edu.vanderbilt.isis.meta.CdbMsg.Notice getNotices(int index) {
      return notices_.get(index);
    }
    public edu.vanderbilt.isis.meta.CdbMsg.NoticeOrBuilder getNoticesOrBuilder(
        int index) {
      return notices_.get(index);
    }
    
    private void initFields() {
      type_ = edu.vanderbilt.isis.meta.CdbMsg.Message.MessageType.INTEREST;
      Id_ = edu.vanderbilt.isis.meta.XsdTypes.ID.getDefaultInstance();
      assemblies_ = edu.vanderbilt.isis.meta.AssemblyInterface.Assemblies.getDefaultInstance();
      notices_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasId()) {
        if (!getId().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasAssemblies()) {
        if (!getAssemblies().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getNoticesCount(); i++) {
        if (!getNotices(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, Id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, assemblies_);
      }
      for (int i = 0; i < notices_.size(); i++) {
        output.writeMessage(4, notices_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, Id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, assemblies_);
      }
      for (int i = 0; i < notices_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, notices_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static edu.vanderbilt.isis.meta.CdbMsg.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.vanderbilt.isis.meta.CdbMsg.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.vanderbilt.isis.meta.CdbMsg.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.vanderbilt.isis.meta.CdbMsg.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.vanderbilt.isis.meta.CdbMsg.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.vanderbilt.isis.meta.CdbMsg.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static edu.vanderbilt.isis.meta.CdbMsg.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.vanderbilt.isis.meta.CdbMsg.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.vanderbilt.isis.meta.CdbMsg.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.vanderbilt.isis.meta.CdbMsg.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.vanderbilt.isis.meta.CdbMsg.Message prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements edu.vanderbilt.isis.meta.CdbMsg.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.vanderbilt.isis.meta.CdbMsg.internal_static_edu_vanderbilt_isis_meta_Message_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.vanderbilt.isis.meta.CdbMsg.internal_static_edu_vanderbilt_isis_meta_Message_fieldAccessorTable;
      }
      
      // Construct using edu.vanderbilt.isis.meta.CdbMsg.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getIdFieldBuilder();
          getAssembliesFieldBuilder();
          getNoticesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        type_ = edu.vanderbilt.isis.meta.CdbMsg.Message.MessageType.INTEREST;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (IdBuilder_ == null) {
          Id_ = edu.vanderbilt.isis.meta.XsdTypes.ID.getDefaultInstance();
        } else {
          IdBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (assembliesBuilder_ == null) {
          assemblies_ = edu.vanderbilt.isis.meta.AssemblyInterface.Assemblies.getDefaultInstance();
        } else {
          assembliesBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        if (noticesBuilder_ == null) {
          notices_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          noticesBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.vanderbilt.isis.meta.CdbMsg.Message.getDescriptor();
      }
      
      public edu.vanderbilt.isis.meta.CdbMsg.Message getDefaultInstanceForType() {
        return edu.vanderbilt.isis.meta.CdbMsg.Message.getDefaultInstance();
      }
      
      public edu.vanderbilt.isis.meta.CdbMsg.Message build() {
        edu.vanderbilt.isis.meta.CdbMsg.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private edu.vanderbilt.isis.meta.CdbMsg.Message buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        edu.vanderbilt.isis.meta.CdbMsg.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public edu.vanderbilt.isis.meta.CdbMsg.Message buildPartial() {
        edu.vanderbilt.isis.meta.CdbMsg.Message result = new edu.vanderbilt.isis.meta.CdbMsg.Message(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (IdBuilder_ == null) {
          result.Id_ = Id_;
        } else {
          result.Id_ = IdBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (assembliesBuilder_ == null) {
          result.assemblies_ = assemblies_;
        } else {
          result.assemblies_ = assembliesBuilder_.build();
        }
        if (noticesBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            notices_ = java.util.Collections.unmodifiableList(notices_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.notices_ = notices_;
        } else {
          result.notices_ = noticesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.vanderbilt.isis.meta.CdbMsg.Message) {
          return mergeFrom((edu.vanderbilt.isis.meta.CdbMsg.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(edu.vanderbilt.isis.meta.CdbMsg.Message other) {
        if (other == edu.vanderbilt.isis.meta.CdbMsg.Message.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasId()) {
          mergeId(other.getId());
        }
        if (other.hasAssemblies()) {
          mergeAssemblies(other.getAssemblies());
        }
        if (noticesBuilder_ == null) {
          if (!other.notices_.isEmpty()) {
            if (notices_.isEmpty()) {
              notices_ = other.notices_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureNoticesIsMutable();
              notices_.addAll(other.notices_);
            }
            onChanged();
          }
        } else {
          if (!other.notices_.isEmpty()) {
            if (noticesBuilder_.isEmpty()) {
              noticesBuilder_.dispose();
              noticesBuilder_ = null;
              notices_ = other.notices_;
              bitField0_ = (bitField0_ & ~0x00000008);
              noticesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getNoticesFieldBuilder() : null;
            } else {
              noticesBuilder_.addAllMessages(other.notices_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (hasId()) {
          if (!getId().isInitialized()) {
            
            return false;
          }
        }
        if (hasAssemblies()) {
          if (!getAssemblies().isInitialized()) {
            
            return false;
          }
        }
        for (int i = 0; i < getNoticesCount(); i++) {
          if (!getNotices(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              edu.vanderbilt.isis.meta.CdbMsg.Message.MessageType value = edu.vanderbilt.isis.meta.CdbMsg.Message.MessageType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 18: {
              edu.vanderbilt.isis.meta.XsdTypes.ID.Builder subBuilder = edu.vanderbilt.isis.meta.XsdTypes.ID.newBuilder();
              if (hasId()) {
                subBuilder.mergeFrom(getId());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setId(subBuilder.buildPartial());
              break;
            }
            case 26: {
              edu.vanderbilt.isis.meta.AssemblyInterface.Assemblies.Builder subBuilder = edu.vanderbilt.isis.meta.AssemblyInterface.Assemblies.newBuilder();
              if (hasAssemblies()) {
                subBuilder.mergeFrom(getAssemblies());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setAssemblies(subBuilder.buildPartial());
              break;
            }
            case 34: {
              edu.vanderbilt.isis.meta.CdbMsg.Notice.Builder subBuilder = edu.vanderbilt.isis.meta.CdbMsg.Notice.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addNotices(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .edu.vanderbilt.isis.meta.Message.MessageType type = 1;
      private edu.vanderbilt.isis.meta.CdbMsg.Message.MessageType type_ = edu.vanderbilt.isis.meta.CdbMsg.Message.MessageType.INTEREST;
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public edu.vanderbilt.isis.meta.CdbMsg.Message.MessageType getType() {
        return type_;
      }
      public Builder setType(edu.vanderbilt.isis.meta.CdbMsg.Message.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = edu.vanderbilt.isis.meta.CdbMsg.Message.MessageType.INTEREST;
        onChanged();
        return this;
      }
      
      // optional .edu.vanderbilt.isis.meta.ID _id = 2;
      private edu.vanderbilt.isis.meta.XsdTypes.ID Id_ = edu.vanderbilt.isis.meta.XsdTypes.ID.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          edu.vanderbilt.isis.meta.XsdTypes.ID, edu.vanderbilt.isis.meta.XsdTypes.ID.Builder, edu.vanderbilt.isis.meta.XsdTypes.IDOrBuilder> IdBuilder_;
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public edu.vanderbilt.isis.meta.XsdTypes.ID getId() {
        if (IdBuilder_ == null) {
          return Id_;
        } else {
          return IdBuilder_.getMessage();
        }
      }
      public Builder setId(edu.vanderbilt.isis.meta.XsdTypes.ID value) {
        if (IdBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          Id_ = value;
          onChanged();
        } else {
          IdBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setId(
          edu.vanderbilt.isis.meta.XsdTypes.ID.Builder builderForValue) {
        if (IdBuilder_ == null) {
          Id_ = builderForValue.build();
          onChanged();
        } else {
          IdBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergeId(edu.vanderbilt.isis.meta.XsdTypes.ID value) {
        if (IdBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              Id_ != edu.vanderbilt.isis.meta.XsdTypes.ID.getDefaultInstance()) {
            Id_ =
              edu.vanderbilt.isis.meta.XsdTypes.ID.newBuilder(Id_).mergeFrom(value).buildPartial();
          } else {
            Id_ = value;
          }
          onChanged();
        } else {
          IdBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearId() {
        if (IdBuilder_ == null) {
          Id_ = edu.vanderbilt.isis.meta.XsdTypes.ID.getDefaultInstance();
          onChanged();
        } else {
          IdBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      public edu.vanderbilt.isis.meta.XsdTypes.ID.Builder getIdBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getIdFieldBuilder().getBuilder();
      }
      public edu.vanderbilt.isis.meta.XsdTypes.IDOrBuilder getIdOrBuilder() {
        if (IdBuilder_ != null) {
          return IdBuilder_.getMessageOrBuilder();
        } else {
          return Id_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          edu.vanderbilt.isis.meta.XsdTypes.ID, edu.vanderbilt.isis.meta.XsdTypes.ID.Builder, edu.vanderbilt.isis.meta.XsdTypes.IDOrBuilder> 
          getIdFieldBuilder() {
        if (IdBuilder_ == null) {
          IdBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              edu.vanderbilt.isis.meta.XsdTypes.ID, edu.vanderbilt.isis.meta.XsdTypes.ID.Builder, edu.vanderbilt.isis.meta.XsdTypes.IDOrBuilder>(
                  Id_,
                  getParentForChildren(),
                  isClean());
          Id_ = null;
        }
        return IdBuilder_;
      }
      
      // optional .edu.vanderbilt.isis.meta.Assemblies assemblies = 3;
      private edu.vanderbilt.isis.meta.AssemblyInterface.Assemblies assemblies_ = edu.vanderbilt.isis.meta.AssemblyInterface.Assemblies.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          edu.vanderbilt.isis.meta.AssemblyInterface.Assemblies, edu.vanderbilt.isis.meta.AssemblyInterface.Assemblies.Builder, edu.vanderbilt.isis.meta.AssemblyInterface.AssembliesOrBuilder> assembliesBuilder_;
      public boolean hasAssemblies() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public edu.vanderbilt.isis.meta.AssemblyInterface.Assemblies getAssemblies() {
        if (assembliesBuilder_ == null) {
          return assemblies_;
        } else {
          return assembliesBuilder_.getMessage();
        }
      }
      public Builder setAssemblies(edu.vanderbilt.isis.meta.AssemblyInterface.Assemblies value) {
        if (assembliesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          assemblies_ = value;
          onChanged();
        } else {
          assembliesBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder setAssemblies(
          edu.vanderbilt.isis.meta.AssemblyInterface.Assemblies.Builder builderForValue) {
        if (assembliesBuilder_ == null) {
          assemblies_ = builderForValue.build();
          onChanged();
        } else {
          assembliesBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder mergeAssemblies(edu.vanderbilt.isis.meta.AssemblyInterface.Assemblies value) {
        if (assembliesBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              assemblies_ != edu.vanderbilt.isis.meta.AssemblyInterface.Assemblies.getDefaultInstance()) {
            assemblies_ =
              edu.vanderbilt.isis.meta.AssemblyInterface.Assemblies.newBuilder(assemblies_).mergeFrom(value).buildPartial();
          } else {
            assemblies_ = value;
          }
          onChanged();
        } else {
          assembliesBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder clearAssemblies() {
        if (assembliesBuilder_ == null) {
          assemblies_ = edu.vanderbilt.isis.meta.AssemblyInterface.Assemblies.getDefaultInstance();
          onChanged();
        } else {
          assembliesBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      public edu.vanderbilt.isis.meta.AssemblyInterface.Assemblies.Builder getAssembliesBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getAssembliesFieldBuilder().getBuilder();
      }
      public edu.vanderbilt.isis.meta.AssemblyInterface.AssembliesOrBuilder getAssembliesOrBuilder() {
        if (assembliesBuilder_ != null) {
          return assembliesBuilder_.getMessageOrBuilder();
        } else {
          return assemblies_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          edu.vanderbilt.isis.meta.AssemblyInterface.Assemblies, edu.vanderbilt.isis.meta.AssemblyInterface.Assemblies.Builder, edu.vanderbilt.isis.meta.AssemblyInterface.AssembliesOrBuilder> 
          getAssembliesFieldBuilder() {
        if (assembliesBuilder_ == null) {
          assembliesBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              edu.vanderbilt.isis.meta.AssemblyInterface.Assemblies, edu.vanderbilt.isis.meta.AssemblyInterface.Assemblies.Builder, edu.vanderbilt.isis.meta.AssemblyInterface.AssembliesOrBuilder>(
                  assemblies_,
                  getParentForChildren(),
                  isClean());
          assemblies_ = null;
        }
        return assembliesBuilder_;
      }
      
      // repeated .edu.vanderbilt.isis.meta.Notice notices = 4;
      private java.util.List<edu.vanderbilt.isis.meta.CdbMsg.Notice> notices_ =
        java.util.Collections.emptyList();
      private void ensureNoticesIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          notices_ = new java.util.ArrayList<edu.vanderbilt.isis.meta.CdbMsg.Notice>(notices_);
          bitField0_ |= 0x00000008;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          edu.vanderbilt.isis.meta.CdbMsg.Notice, edu.vanderbilt.isis.meta.CdbMsg.Notice.Builder, edu.vanderbilt.isis.meta.CdbMsg.NoticeOrBuilder> noticesBuilder_;
      
      public java.util.List<edu.vanderbilt.isis.meta.CdbMsg.Notice> getNoticesList() {
        if (noticesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(notices_);
        } else {
          return noticesBuilder_.getMessageList();
        }
      }
      public int getNoticesCount() {
        if (noticesBuilder_ == null) {
          return notices_.size();
        } else {
          return noticesBuilder_.getCount();
        }
      }
      public edu.vanderbilt.isis.meta.CdbMsg.Notice getNotices(int index) {
        if (noticesBuilder_ == null) {
          return notices_.get(index);
        } else {
          return noticesBuilder_.getMessage(index);
        }
      }
      public Builder setNotices(
          int index, edu.vanderbilt.isis.meta.CdbMsg.Notice value) {
        if (noticesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNoticesIsMutable();
          notices_.set(index, value);
          onChanged();
        } else {
          noticesBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setNotices(
          int index, edu.vanderbilt.isis.meta.CdbMsg.Notice.Builder builderForValue) {
        if (noticesBuilder_ == null) {
          ensureNoticesIsMutable();
          notices_.set(index, builderForValue.build());
          onChanged();
        } else {
          noticesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addNotices(edu.vanderbilt.isis.meta.CdbMsg.Notice value) {
        if (noticesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNoticesIsMutable();
          notices_.add(value);
          onChanged();
        } else {
          noticesBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addNotices(
          int index, edu.vanderbilt.isis.meta.CdbMsg.Notice value) {
        if (noticesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNoticesIsMutable();
          notices_.add(index, value);
          onChanged();
        } else {
          noticesBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addNotices(
          edu.vanderbilt.isis.meta.CdbMsg.Notice.Builder builderForValue) {
        if (noticesBuilder_ == null) {
          ensureNoticesIsMutable();
          notices_.add(builderForValue.build());
          onChanged();
        } else {
          noticesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addNotices(
          int index, edu.vanderbilt.isis.meta.CdbMsg.Notice.Builder builderForValue) {
        if (noticesBuilder_ == null) {
          ensureNoticesIsMutable();
          notices_.add(index, builderForValue.build());
          onChanged();
        } else {
          noticesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllNotices(
          java.lang.Iterable<? extends edu.vanderbilt.isis.meta.CdbMsg.Notice> values) {
        if (noticesBuilder_ == null) {
          ensureNoticesIsMutable();
          super.addAll(values, notices_);
          onChanged();
        } else {
          noticesBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearNotices() {
        if (noticesBuilder_ == null) {
          notices_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          noticesBuilder_.clear();
        }
        return this;
      }
      public Builder removeNotices(int index) {
        if (noticesBuilder_ == null) {
          ensureNoticesIsMutable();
          notices_.remove(index);
          onChanged();
        } else {
          noticesBuilder_.remove(index);
        }
        return this;
      }
      public edu.vanderbilt.isis.meta.CdbMsg.Notice.Builder getNoticesBuilder(
          int index) {
        return getNoticesFieldBuilder().getBuilder(index);
      }
      public edu.vanderbilt.isis.meta.CdbMsg.NoticeOrBuilder getNoticesOrBuilder(
          int index) {
        if (noticesBuilder_ == null) {
          return notices_.get(index);  } else {
          return noticesBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends edu.vanderbilt.isis.meta.CdbMsg.NoticeOrBuilder> 
           getNoticesOrBuilderList() {
        if (noticesBuilder_ != null) {
          return noticesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(notices_);
        }
      }
      public edu.vanderbilt.isis.meta.CdbMsg.Notice.Builder addNoticesBuilder() {
        return getNoticesFieldBuilder().addBuilder(
            edu.vanderbilt.isis.meta.CdbMsg.Notice.getDefaultInstance());
      }
      public edu.vanderbilt.isis.meta.CdbMsg.Notice.Builder addNoticesBuilder(
          int index) {
        return getNoticesFieldBuilder().addBuilder(
            index, edu.vanderbilt.isis.meta.CdbMsg.Notice.getDefaultInstance());
      }
      public java.util.List<edu.vanderbilt.isis.meta.CdbMsg.Notice.Builder> 
           getNoticesBuilderList() {
        return getNoticesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          edu.vanderbilt.isis.meta.CdbMsg.Notice, edu.vanderbilt.isis.meta.CdbMsg.Notice.Builder, edu.vanderbilt.isis.meta.CdbMsg.NoticeOrBuilder> 
          getNoticesFieldBuilder() {
        if (noticesBuilder_ == null) {
          noticesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              edu.vanderbilt.isis.meta.CdbMsg.Notice, edu.vanderbilt.isis.meta.CdbMsg.Notice.Builder, edu.vanderbilt.isis.meta.CdbMsg.NoticeOrBuilder>(
                  notices_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          notices_ = null;
        }
        return noticesBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:edu.vanderbilt.isis.meta.Message)
    }
    
    static {
      defaultInstance = new Message(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:edu.vanderbilt.isis.meta.Message)
  }
  
  public interface NoticeOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .edu.vanderbilt.isis.meta.Notice.NoticeType type = 1;
    boolean hasType();
    edu.vanderbilt.isis.meta.CdbMsg.Notice.NoticeType getType();
    
    // optional .edu.vanderbilt.isis.meta.ID _id = 2;
    boolean hasId();
    edu.vanderbilt.isis.meta.XsdTypes.ID getId();
    edu.vanderbilt.isis.meta.XsdTypes.IDOrBuilder getIdOrBuilder();
    
    // optional string msg = 3;
    boolean hasMsg();
    String getMsg();
    
    // optional string code = 4;
    boolean hasCode();
    String getCode();
  }
  public static final class Notice extends
      com.google.protobuf.GeneratedMessage
      implements NoticeOrBuilder {
    // Use Notice.newBuilder() to construct.
    private Notice(Builder builder) {
      super(builder);
    }
    private Notice(boolean noInit) {}
    
    private static final Notice defaultInstance;
    public static Notice getDefaultInstance() {
      return defaultInstance;
    }
    
    public Notice getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.vanderbilt.isis.meta.CdbMsg.internal_static_edu_vanderbilt_isis_meta_Notice_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.vanderbilt.isis.meta.CdbMsg.internal_static_edu_vanderbilt_isis_meta_Notice_fieldAccessorTable;
    }
    
    public enum NoticeType
        implements com.google.protobuf.ProtocolMessageEnum {
      FAIL(0, 0),
      REJECT(1, 1),
      ERROR(2, 2),
      WARN(3, 3),
      INFO(4, 4),
      ACK(5, 5),
      ;
      
      public static final int FAIL_VALUE = 0;
      public static final int REJECT_VALUE = 1;
      public static final int ERROR_VALUE = 2;
      public static final int WARN_VALUE = 3;
      public static final int INFO_VALUE = 4;
      public static final int ACK_VALUE = 5;
      
      
      public final int getNumber() { return value; }
      
      public static NoticeType valueOf(int value) {
        switch (value) {
          case 0: return FAIL;
          case 1: return REJECT;
          case 2: return ERROR;
          case 3: return WARN;
          case 4: return INFO;
          case 5: return ACK;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<NoticeType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<NoticeType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<NoticeType>() {
              public NoticeType findValueByNumber(int number) {
                return NoticeType.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return edu.vanderbilt.isis.meta.CdbMsg.Notice.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final NoticeType[] VALUES = {
        FAIL, REJECT, ERROR, WARN, INFO, ACK, 
      };
      
      public static NoticeType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private NoticeType(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:edu.vanderbilt.isis.meta.Notice.NoticeType)
    }
    
    private int bitField0_;
    // required .edu.vanderbilt.isis.meta.Notice.NoticeType type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private edu.vanderbilt.isis.meta.CdbMsg.Notice.NoticeType type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public edu.vanderbilt.isis.meta.CdbMsg.Notice.NoticeType getType() {
      return type_;
    }
    
    // optional .edu.vanderbilt.isis.meta.ID _id = 2;
    public static final int _ID_FIELD_NUMBER = 2;
    private edu.vanderbilt.isis.meta.XsdTypes.ID Id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public edu.vanderbilt.isis.meta.XsdTypes.ID getId() {
      return Id_;
    }
    public edu.vanderbilt.isis.meta.XsdTypes.IDOrBuilder getIdOrBuilder() {
      return Id_;
    }
    
    // optional string msg = 3;
    public static final int MSG_FIELD_NUMBER = 3;
    private java.lang.Object msg_;
    public boolean hasMsg() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getMsg() {
      java.lang.Object ref = msg_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          msg_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string code = 4;
    public static final int CODE_FIELD_NUMBER = 4;
    private java.lang.Object code_;
    public boolean hasCode() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getCode() {
      java.lang.Object ref = code_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          code_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getCodeBytes() {
      java.lang.Object ref = code_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        code_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      type_ = edu.vanderbilt.isis.meta.CdbMsg.Notice.NoticeType.FAIL;
      Id_ = edu.vanderbilt.isis.meta.XsdTypes.ID.getDefaultInstance();
      msg_ = "";
      code_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasId()) {
        if (!getId().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, Id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getMsgBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getCodeBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, Id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getMsgBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getCodeBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static edu.vanderbilt.isis.meta.CdbMsg.Notice parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.vanderbilt.isis.meta.CdbMsg.Notice parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.vanderbilt.isis.meta.CdbMsg.Notice parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.vanderbilt.isis.meta.CdbMsg.Notice parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.vanderbilt.isis.meta.CdbMsg.Notice parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.vanderbilt.isis.meta.CdbMsg.Notice parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static edu.vanderbilt.isis.meta.CdbMsg.Notice parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.vanderbilt.isis.meta.CdbMsg.Notice parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.vanderbilt.isis.meta.CdbMsg.Notice parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.vanderbilt.isis.meta.CdbMsg.Notice parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.vanderbilt.isis.meta.CdbMsg.Notice prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements edu.vanderbilt.isis.meta.CdbMsg.NoticeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.vanderbilt.isis.meta.CdbMsg.internal_static_edu_vanderbilt_isis_meta_Notice_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.vanderbilt.isis.meta.CdbMsg.internal_static_edu_vanderbilt_isis_meta_Notice_fieldAccessorTable;
      }
      
      // Construct using edu.vanderbilt.isis.meta.CdbMsg.Notice.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getIdFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        type_ = edu.vanderbilt.isis.meta.CdbMsg.Notice.NoticeType.FAIL;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (IdBuilder_ == null) {
          Id_ = edu.vanderbilt.isis.meta.XsdTypes.ID.getDefaultInstance();
        } else {
          IdBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        msg_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        code_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.vanderbilt.isis.meta.CdbMsg.Notice.getDescriptor();
      }
      
      public edu.vanderbilt.isis.meta.CdbMsg.Notice getDefaultInstanceForType() {
        return edu.vanderbilt.isis.meta.CdbMsg.Notice.getDefaultInstance();
      }
      
      public edu.vanderbilt.isis.meta.CdbMsg.Notice build() {
        edu.vanderbilt.isis.meta.CdbMsg.Notice result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private edu.vanderbilt.isis.meta.CdbMsg.Notice buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        edu.vanderbilt.isis.meta.CdbMsg.Notice result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public edu.vanderbilt.isis.meta.CdbMsg.Notice buildPartial() {
        edu.vanderbilt.isis.meta.CdbMsg.Notice result = new edu.vanderbilt.isis.meta.CdbMsg.Notice(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (IdBuilder_ == null) {
          result.Id_ = Id_;
        } else {
          result.Id_ = IdBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.msg_ = msg_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.code_ = code_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.vanderbilt.isis.meta.CdbMsg.Notice) {
          return mergeFrom((edu.vanderbilt.isis.meta.CdbMsg.Notice)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(edu.vanderbilt.isis.meta.CdbMsg.Notice other) {
        if (other == edu.vanderbilt.isis.meta.CdbMsg.Notice.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasId()) {
          mergeId(other.getId());
        }
        if (other.hasMsg()) {
          setMsg(other.getMsg());
        }
        if (other.hasCode()) {
          setCode(other.getCode());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (hasId()) {
          if (!getId().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              edu.vanderbilt.isis.meta.CdbMsg.Notice.NoticeType value = edu.vanderbilt.isis.meta.CdbMsg.Notice.NoticeType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 18: {
              edu.vanderbilt.isis.meta.XsdTypes.ID.Builder subBuilder = edu.vanderbilt.isis.meta.XsdTypes.ID.newBuilder();
              if (hasId()) {
                subBuilder.mergeFrom(getId());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setId(subBuilder.buildPartial());
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              msg_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              code_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .edu.vanderbilt.isis.meta.Notice.NoticeType type = 1;
      private edu.vanderbilt.isis.meta.CdbMsg.Notice.NoticeType type_ = edu.vanderbilt.isis.meta.CdbMsg.Notice.NoticeType.FAIL;
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public edu.vanderbilt.isis.meta.CdbMsg.Notice.NoticeType getType() {
        return type_;
      }
      public Builder setType(edu.vanderbilt.isis.meta.CdbMsg.Notice.NoticeType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = edu.vanderbilt.isis.meta.CdbMsg.Notice.NoticeType.FAIL;
        onChanged();
        return this;
      }
      
      // optional .edu.vanderbilt.isis.meta.ID _id = 2;
      private edu.vanderbilt.isis.meta.XsdTypes.ID Id_ = edu.vanderbilt.isis.meta.XsdTypes.ID.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          edu.vanderbilt.isis.meta.XsdTypes.ID, edu.vanderbilt.isis.meta.XsdTypes.ID.Builder, edu.vanderbilt.isis.meta.XsdTypes.IDOrBuilder> IdBuilder_;
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public edu.vanderbilt.isis.meta.XsdTypes.ID getId() {
        if (IdBuilder_ == null) {
          return Id_;
        } else {
          return IdBuilder_.getMessage();
        }
      }
      public Builder setId(edu.vanderbilt.isis.meta.XsdTypes.ID value) {
        if (IdBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          Id_ = value;
          onChanged();
        } else {
          IdBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setId(
          edu.vanderbilt.isis.meta.XsdTypes.ID.Builder builderForValue) {
        if (IdBuilder_ == null) {
          Id_ = builderForValue.build();
          onChanged();
        } else {
          IdBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergeId(edu.vanderbilt.isis.meta.XsdTypes.ID value) {
        if (IdBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              Id_ != edu.vanderbilt.isis.meta.XsdTypes.ID.getDefaultInstance()) {
            Id_ =
              edu.vanderbilt.isis.meta.XsdTypes.ID.newBuilder(Id_).mergeFrom(value).buildPartial();
          } else {
            Id_ = value;
          }
          onChanged();
        } else {
          IdBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearId() {
        if (IdBuilder_ == null) {
          Id_ = edu.vanderbilt.isis.meta.XsdTypes.ID.getDefaultInstance();
          onChanged();
        } else {
          IdBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      public edu.vanderbilt.isis.meta.XsdTypes.ID.Builder getIdBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getIdFieldBuilder().getBuilder();
      }
      public edu.vanderbilt.isis.meta.XsdTypes.IDOrBuilder getIdOrBuilder() {
        if (IdBuilder_ != null) {
          return IdBuilder_.getMessageOrBuilder();
        } else {
          return Id_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          edu.vanderbilt.isis.meta.XsdTypes.ID, edu.vanderbilt.isis.meta.XsdTypes.ID.Builder, edu.vanderbilt.isis.meta.XsdTypes.IDOrBuilder> 
          getIdFieldBuilder() {
        if (IdBuilder_ == null) {
          IdBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              edu.vanderbilt.isis.meta.XsdTypes.ID, edu.vanderbilt.isis.meta.XsdTypes.ID.Builder, edu.vanderbilt.isis.meta.XsdTypes.IDOrBuilder>(
                  Id_,
                  getParentForChildren(),
                  isClean());
          Id_ = null;
        }
        return IdBuilder_;
      }
      
      // optional string msg = 3;
      private java.lang.Object msg_ = "";
      public boolean hasMsg() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getMsg() {
        java.lang.Object ref = msg_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          msg_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setMsg(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        msg_ = value;
        onChanged();
        return this;
      }
      public Builder clearMsg() {
        bitField0_ = (bitField0_ & ~0x00000004);
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      void setMsg(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        msg_ = value;
        onChanged();
      }
      
      // optional string code = 4;
      private java.lang.Object code_ = "";
      public boolean hasCode() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getCode() {
        java.lang.Object ref = code_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          code_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setCode(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        code_ = value;
        onChanged();
        return this;
      }
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000008);
        code_ = getDefaultInstance().getCode();
        onChanged();
        return this;
      }
      void setCode(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        code_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:edu.vanderbilt.isis.meta.Notice)
    }
    
    static {
      defaultInstance = new Notice(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:edu.vanderbilt.isis.meta.Notice)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_edu_vanderbilt_isis_meta_Message_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_edu_vanderbilt_isis_meta_Message_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_edu_vanderbilt_isis_meta_Notice_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_edu_vanderbilt_isis_meta_Notice_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014CdbMsg.proto\022\030edu.vanderbilt.isis.meta" +
      "\032\016XsdTypes.proto\032\027AssemblyInterface.prot" +
      "o\"\234\002\n\007Message\022;\n\004type\030\001 \002(\0162-.edu.vander" +
      "bilt.isis.meta.Message.MessageType\022)\n\003_i" +
      "d\030\002 \001(\0132\034.edu.vanderbilt.isis.meta.ID\0228\n" +
      "\nassemblies\030\003 \001(\0132$.edu.vanderbilt.isis." +
      "meta.Assemblies\0221\n\007notices\030\004 \003(\0132 .edu.v" +
      "anderbilt.isis.meta.Notice\"<\n\013MessageTyp" +
      "e\022\014\n\010INTEREST\020\000\022\n\n\006UPDATE\020\001\022\010\n\004FILL\020\002\022\t\n" +
      "\005TRASH\020\003\"\325\001\n\006Notice\0229\n\004type\030\001 \002(\0162+.edu.",
      "vanderbilt.isis.meta.Notice.NoticeType\022)" +
      "\n\003_id\030\002 \001(\0132\034.edu.vanderbilt.isis.meta.I" +
      "D\022\013\n\003msg\030\003 \001(\t\022\014\n\004code\030\004 \001(\t\"J\n\nNoticeTy" +
      "pe\022\010\n\004FAIL\020\000\022\n\n\006REJECT\020\001\022\t\n\005ERROR\020\002\022\010\n\004W" +
      "ARN\020\003\022\010\n\004INFO\020\004\022\007\n\003ACK\020\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_edu_vanderbilt_isis_meta_Message_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_edu_vanderbilt_isis_meta_Message_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_edu_vanderbilt_isis_meta_Message_descriptor,
              new java.lang.String[] { "Type", "Id", "Assemblies", "Notices", },
              edu.vanderbilt.isis.meta.CdbMsg.Message.class,
              edu.vanderbilt.isis.meta.CdbMsg.Message.Builder.class);
          internal_static_edu_vanderbilt_isis_meta_Notice_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_edu_vanderbilt_isis_meta_Notice_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_edu_vanderbilt_isis_meta_Notice_descriptor,
              new java.lang.String[] { "Type", "Id", "Msg", "Code", },
              edu.vanderbilt.isis.meta.CdbMsg.Notice.class,
              edu.vanderbilt.isis.meta.CdbMsg.Notice.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          edu.vanderbilt.isis.meta.XsdTypes.getDescriptor(),
          edu.vanderbilt.isis.meta.AssemblyInterface.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
